version: "3.8"
services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  app:
    build: .
    container_name: flask-app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DB_NAME=clientes_db
    ports:
      - "5000:5000"
    restart: unless-stopped

volumes:
  mongo-data:
